language: python
sudo: false
cache:
  directories:
  - cache/

before_install:
  - ./get_app_engine_sdk.sh
  - ./get_gcd_zip.sh
  - export GAE="./cache/google_appengine"
  - export GCD_ZIP="./cache/cloud-datastore-emulator-1.3.0.zip"

install:
  - pip install tox

script:
  - tox

env:
  - TOXENV=py27

after_success:
  - tox -e coveralls
